name: auth
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0-218.1.beta <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  flutter_native_splash: ^2.2.18
  get_it: ^7.2.0
  get: ^4.6.5
  liquid_swipe: ^3.0.0
  smooth_page_indicator: ^1.0.1
  flutter_otp_text_field: ^1.1.1
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  line_awesome_flutter: ^2.0.0
  cloud_firestore: ^4.4.4
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.1
  zoom_tap_animation: ^1.1.0
  table_calendar: ^3.0.8
  shared_preferences: ^2.0.18
  fluttertoast: ^8.2.1
  scaffold_gradient_background: ^1.0.3+1
  webview_flutter: ^3.0.0
  flutter_dotenv: ^5.0.2
  velocity_x: ^3.6.0
  chat_gpt_sdk:
    git:
      url: https://github.com/iampawan/Flutter-ChatGPT.git
  flutter_spinkit: ^5.1.0
  http: ^0.13.5
  provider: ^6.0.5
  animated_text_kit: ^4.2.2
  firebase_messaging: ^14.4.1
  flutter_local_notifications: ^14.0.0+1
  app_settings: ^4.3.1
  url_launcher: ^6.1.11
  flutter_svg: ^2.0.5
  intl: ^0.17.0
  assets_audio_player: ^3.0.6
  another_transformer_page_view: ^2.0.1
  carousel_slider: ^4.2.1
  youtube_player_flutter: ^8.1.2
  email_validator: ^2.1.17
  flutter_riverpod: ^2.3.6
  go_router: ^7.1.1
  dynamic_color: ^1.6.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fl_chart: ^0.63.0
  timeline_tile: ^2.0.0
  state_notifier: ^0.7.2+1



dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  build_runner: ^2.3.3 
  hive_generator: ^2.0.0
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  flutter_gen_runner: ^5.3.0

flutter_native_splash:
  color: "#f7f6f1"
  color_dark: "#f7f6f1"
  image: assets/images/welcome_images/welcome.png
  image_dark: assets/images/welcome_images/welcome.png

android_12:
  image: assets/images/welcome_images/welcome.png
  icon_background_color: "#f7f6f1"
  image_dark: assets/images/welcome_images/welcome.png
  icon_background_color_dark: "#272727"

flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/onboarding_images/activity.png
    - assets/images/onboarding_images/calender.png
    - assets/images/onboarding_images/pmood.png
    - assets/images/mood.jpg
    - assets/images/moodtrack.JPG
    - assets/images/one.jpg
    - assets/images/second.jpg
    - assets/images/welcome_images/welcome.png
    - assets/logo/google-logo.png
    - assets/images/dashboard/dash-person.jpeg
    - assets/images/chatbot/chat_logo.png
    - assets/images/chatbot/openai_logo.jpg
    - assets/images/chatbot/person.png
    - assets/page-1/images/man-and-woman-sitting-at-the-cafe-and-talking.png
    - assets/page-1/images/employees-working-on-task-management.png
    - assets/page-1/images/woman-riding-a-skateboard.png
    - assets/page-1/images/pulse.png
    - assets/page-1/images/woman-meditating-on-a-ball.png
    - assets/page-1/images/desk-calendar-with-smiley-face-and-good-mood.png
    - assets/page-1/images/jump-rope-and-dumbbell-for-workout.png
    - assets/page-1/images/game-console-with-game-icons.png
    - assets/page-1/images/bubbleimg.png
    - assets/images/creative.png
    - assets/images/otdoor.png
    - assets/images/social.png
    - assets/images/relax.png
    - assets/images/
    - assets/audio/
    - assets/images/mood_icons/
    - assets/page-1/images/your-personal-diary.png
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf